server:
  port: 8080

spring:
  application:
    name: backend-simsml
  datasource:
    url: jdbc:postgresql://localhost:5432/db-simsml
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:init.sql

security:
  jwt:
    key:
      private: 709e5f4de55e726a13a89d1cc875ca90f23464610aec6f0efb716b997fffcb91
    user:
      generator: AUTH0JWT-SIMSML-BACKEND